# Generated by Django 5.1.7 on 2025-03-26 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staticdata", "0008_examples_theory"),
        ("visoraai", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="iframeresponse",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="staticdata.project",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="iframeresponse",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="staticdata.usernamedb",
            ),
            preserve_default=False,
        ),
    ]
