# Generated by Django 5.1.7 on 2025-03-15 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staticdata", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name="projectfile",
            old_name="created_at",
            new_name="uploaded_at",
        ),
        migrations.RemoveField(
            model_name="projectfile",
            name="checksum",
        ),
        migrations.RemoveField(
            model_name="projectfile",
            name="content",
        ),
        migrations.RemoveField(
            model_name="projectfile",
            name="file_name",
        ),
        migrations.RemoveField(
            model_name="projectfile",
            name="file_type",
        ),
        migrations.AlterField(
            model_name="projectfile",
            name="file",
            field=models.FileField(default=1, upload_to="user_uploads/%Y/%m/%d/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="projectfile",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="staticdata.project",
            ),
        ),
        migrations.DeleteModel(
            name="UserProject",
        ),
    ]
