# Generated by Django 5.1.7 on 2025-03-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "staticdata",
            "0002_project_rename_created_at_projectfile_uploaded_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="project_name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
