# Generated by Django 5.1.7 on 2025-03-18 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staticdata", "0002_usernamedb_alter_project_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectcomment",
            name="user_token",
        ),
        migrations.RemoveField(
            model_name="projectlike",
            name="user_token",
        ),
        migrations.AddField(
            model_name="projectcomment",
            name="username",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usernamecomment",
                to="staticdata.usernamedb",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projectlike",
            name="username",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usernamelike",
                to="staticdata.usernamedb",
            ),
            preserve_default=False,
        ),
    ]
