# Generated by Django 5.1.7 on 2025-03-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staticdata", "0003_project_project_description_project_project_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="project_description",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="project",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="project",
            name="project_name",
        ),
        migrations.RemoveField(
            model_name="projectfile",
            name="uploaded_at",
        ),
        migrations.RemoveField(
            model_name="projectfile",
            name="version",
        ),
        migrations.AddField(
            model_name="project",
            name="name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="projectfile",
            name="file",
            field=models.FileField(upload_to="projects/"),
        ),
    ]
