# Generated by Django 5.1.7 on 2025-03-15 21:41

import staticdata.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staticdata", "0004_rename_project_description_project_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectfile",
            name="file",
            field=models.FileField(
                upload_to=staticdata.models.ProjectFile.file_upload_path
            ),
        ),
    ]
