# Generated by Django 5.1.7 on 2025-03-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staticdata", "0004_question_option_quiz_question_quiz"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="quiz",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="description",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="title",
        ),
        migrations.AddField(
            model_name="quiz",
            name="data",
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Option",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
    ]
