# Generated by Django 5.1.7 on 2025-03-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staticdata", "0005_remove_question_quiz_remove_quiz_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usernamedb",
            name="profile_picture",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usernamedb",
            name="role",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usernamedb",
            name="userid",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
