# Generated by Django 5.1.7 on 2025-03-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staticdata", "0008_examples_theory"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="gradename",
            field=models.CharField(default="tab", max_length=100),
        ),
        migrations.AddField(
            model_name="project",
            name="subjectname",
            field=models.CharField(default="tab", max_length=100),
        ),
        migrations.AddField(
            model_name="project",
            name="tabname",
            field=models.CharField(default="tab", max_length=100),
        ),
    ]
