# Generated by Django 5.1.7 on 2025-03-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staticdata", "0010_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
