# Generated by Django 5.1.7 on 2025-04-04 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staticdata", "0012_category_category_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSessionData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(default="5.5-html", max_length=20)),
                ("topic", models.CharField(blank=True, default="", max_length=255)),
                ("prerequisites", models.TextField(blank=True, default="")),
                ("duration", models.CharField(blank=True, default="1", max_length=50)),
                (
                    "difficulty",
                    models.CharField(blank=True, default="intermediate", max_length=50),
                ),
                ("theme_mode", models.CharField(default="dark", max_length=20)),
                ("font_size_factor", models.FloatField(default=1.0)),
                ("high_contrast", models.BooleanField(default=False)),
                ("reduce_animations", models.BooleanField(default=False)),
                ("subtopics", models.JSONField(blank=True, default=list)),
                ("plan_data", models.JSONField(blank=True, default=dict)),
                ("review_schedule", models.JSONField(blank=True, default=dict)),
                ("plan_analysis", models.JSONField(blank=True, null=True)),
                ("user_points", models.IntegerField(default=0)),
                ("study_streak", models.IntegerField(default=0)),
                ("earned_badges", models.JSONField(blank=True, default=list)),
                ("last_study_date", models.DateField(blank=True, null=True)),
                ("chat_history", models.JSONField(blank=True, default=list)),
                ("journal_prompts", models.JSONField(blank=True, default=dict)),
                (
                    "selected_subtopic_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_data",
                        to="staticdata.usernamedb",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Session Data",
                "verbose_name_plural": "User Session Data",
                "ordering": ["-updated_at"],
            },
        ),
    ]
