# Generated by Django 5.1.7 on 2025-04-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staticdata", "0013_usersessiondata"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usersessiondata",
            options={
                "ordering": ["anonymous_user_id", "-updated_at"],
                "verbose_name": "User Session Data",
                "verbose_name_plural": "User Session Data",
            },
        ),
        migrations.RemoveField(
            model_name="usersessiondata",
            name="user",
        ),
        migrations.AddField(
            model_name="usersessiondata",
            name="anonymous_user_id",
            field=models.UUIDField(
                db_index=True,
                default=1,
                help_text="UUID identifying the anonymous user/browser.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usersessiondata",
            name="name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="User-friendly name for the session.",
                max_length=255,
            ),
        ),
        migrations.AddIndex(
            model_name="usersessiondata",
            index=models.Index(
                fields=["anonymous_user_id", "-updated_at"],
                name="staticdata__anonymo_5273f8_idx",
            ),
        ),
    ]
