# Generated by Django 5.1.7 on 2025-04-05 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staticdata", "0014_alter_usersessiondata_options_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="usersessiondata",
            new_name="staticdata__anonymo_d7e79c_idx",
            old_name="staticdata__anonymo_5273f8_idx",
        ),
        migrations.AlterField(
            model_name="usersessiondata",
            name="anonymous_user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="staticdata.usernamedb"
            ),
        ),
    ]
