# Generated by Django 5.1.7 on 2025-04-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "staticdata",
            "0015_rename_staticdata__anonymo_5273f8_idx_staticdata__anonymo_d7e79c_idx_and_more",
        ),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="usersessiondata",
            new_name="staticdata__anonymo_5273f8_idx",
            old_name="staticdata__anonymo_d7e79c_idx",
        ),
        migrations.AlterField(
            model_name="usersessiondata",
            name="anonymous_user_id",
            field=models.UUIDField(
                db_index=True, help_text="UUID identifying the anonymous user/browser."
            ),
        ),
    ]
